# Generated by Django 3.1.3 on 2020-11-16 07:35

import blogs.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('article_category', models.CharField(blank=True, choices=[('KG', 'KG'), ('WORLD', 'WORLD'), ('SPORT', 'SPORT')], default='KG', max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=blogs.models.upload_image_path)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
